### PR TITLE
Format source code and update canlib

### PR DESCRIPTION
**Pull request by JasonBrave**
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/cansw_charging/3)

### CODE REVIEW

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
I'm a fan. Would this work if it lived in `canlib` so it's automatically shared everywhere tho? Also can we get a `format.sh` that we can run to format everything since I think most people (eg me) don't know how to use clang-format.

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/cansw_charging/3#-:-NhNBymJ9SXheO5Zl7f4:b-btvuii)* status: all files reviewed, 4 unresolved discussions (waiting on @DomenicHampson, @itslinotlie, and @JasonBrave)

___
*[`.clang-format` line 42 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_charging/3#-NhN988I2e-CMHU2U4g0:-NhN988I2e-CMHU2U4g1:b-9h3wy7) ([raw file](https://github.com/waterloo-rocketry/cansw_charging/blob/d549e7d8c88dee1ae277b227c8fe2bfa2280e962/.clang-format#L42)):*
> ```YAML
> AllowAllArgumentsOnNextLine: true
> AllowAllParametersOfDeclarationOnNextLine: true
> AllowShortBlocksOnASingleLine: Never
> ```

I'd prefer `Empty` to allow cleaner busywaits.
___
*[`.clang-format` line 53 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_charging/3#-NhNB80292UgcQbhrvi5:-NhNB80292UgcQbhrvi6:ba3427u) ([raw file](https://github.com/waterloo-rocketry/cansw_charging/blob/d549e7d8c88dee1ae277b227c8fe2bfa2280e962/.clang-format#L53)):*
> ```YAML
> AlwaysBreakBeforeMultilineStrings: false
> AlwaysBreakTemplateDeclarations: Yes
> BinPackArguments: true
> ```

I think `false` is much more readable (see: building CAN messages in `main.c`).
___
*[`.clang-format` line 110 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_charging/3#-NhNARen30PDm8m9YBPm:-NhNAReo3-2_kTqZxURQ:b-6dlx3r) ([raw file](https://github.com/waterloo-rocketry/cansw_charging/blob/d549e7d8c88dee1ae277b227c8fe2bfa2280e962/.clang-format#L110)):*
> ```YAML
> IndentWidth:     4
> IndentWrappedFunctionNames: false
> InsertBraces:    false
> ```

Personal preference but I'd like this enabled.
___
*[`.clang-format` line 146 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_charging/3#-NhNA-_1D4eZV2kcjCpZ:-NhNA-_1D4eZV2kcjCp_:b-wlrz64) ([raw file](https://github.com/waterloo-rocketry/cansw_charging/blob/d549e7d8c88dee1ae277b227c8fe2bfa2280e962/.clang-format#L146)):*
> ```YAML
> PenaltyIndentedWhitespace: 0
> PenaltyReturnTypeOnItsOwnLine: 60
> PointerAlignment: Left
> ```

I think `Right` is more common and readable (prevents errors like `int* a, b;`)

**Comment by JasonBrave** [comment]
1, 2, 4 Addressed
3 Addressed, braces should always be used, however this makes us always need to inspect code after run formatting, see https://clang.llvm.org/docs/ClangFormatStyleOptions.html#insertbraces

**Review by StarlightDescender — APPROVED** [review]
👍

**Review by Lucifersan — APPROVED** [review]
Me likey

**Pull request merged**
